/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteRouteImport } from './routes/_game/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameTwoDigitSubtractionRouteImport } from './routes/_game/two-digit-subtraction'
import { Route as GameTwoDigitAdditionRouteImport } from './routes/_game/two-digit-addition'
import { Route as GamePowerOfTwoRouteImport } from './routes/_game/power-of-two'
import { Route as GameOneDigitSubtractionRouteImport } from './routes/_game/one-digit-subtraction'
import { Route as GameOneDigitAdditionRouteImport } from './routes/_game/one-digit-addition'
import { Route as GameMultiplicationRouteImport } from './routes/_game/multiplication'
import { Route as GameElevenRouteImport } from './routes/_game/eleven'

const GameRouteRoute = GameRouteRouteImport.update({
  id: '/_game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameTwoDigitSubtractionRoute = GameTwoDigitSubtractionRouteImport.update({
  id: '/two-digit-subtraction',
  path: '/two-digit-subtraction',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameTwoDigitAdditionRoute = GameTwoDigitAdditionRouteImport.update({
  id: '/two-digit-addition',
  path: '/two-digit-addition',
  getParentRoute: () => GameRouteRoute,
} as any)
const GamePowerOfTwoRoute = GamePowerOfTwoRouteImport.update({
  id: '/power-of-two',
  path: '/power-of-two',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameOneDigitSubtractionRoute = GameOneDigitSubtractionRouteImport.update({
  id: '/one-digit-subtraction',
  path: '/one-digit-subtraction',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameOneDigitAdditionRoute = GameOneDigitAdditionRouteImport.update({
  id: '/one-digit-addition',
  path: '/one-digit-addition',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameMultiplicationRoute = GameMultiplicationRouteImport.update({
  id: '/multiplication',
  path: '/multiplication',
  getParentRoute: () => GameRouteRoute,
} as any)
const GameElevenRoute = GameElevenRouteImport.update({
  id: '/eleven',
  path: '/eleven',
  getParentRoute: () => GameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eleven': typeof GameElevenRoute
  '/multiplication': typeof GameMultiplicationRoute
  '/one-digit-addition': typeof GameOneDigitAdditionRoute
  '/one-digit-subtraction': typeof GameOneDigitSubtractionRoute
  '/power-of-two': typeof GamePowerOfTwoRoute
  '/two-digit-addition': typeof GameTwoDigitAdditionRoute
  '/two-digit-subtraction': typeof GameTwoDigitSubtractionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eleven': typeof GameElevenRoute
  '/multiplication': typeof GameMultiplicationRoute
  '/one-digit-addition': typeof GameOneDigitAdditionRoute
  '/one-digit-subtraction': typeof GameOneDigitSubtractionRoute
  '/power-of-two': typeof GamePowerOfTwoRoute
  '/two-digit-addition': typeof GameTwoDigitAdditionRoute
  '/two-digit-subtraction': typeof GameTwoDigitSubtractionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_game': typeof GameRouteRouteWithChildren
  '/_game/eleven': typeof GameElevenRoute
  '/_game/multiplication': typeof GameMultiplicationRoute
  '/_game/one-digit-addition': typeof GameOneDigitAdditionRoute
  '/_game/one-digit-subtraction': typeof GameOneDigitSubtractionRoute
  '/_game/power-of-two': typeof GamePowerOfTwoRoute
  '/_game/two-digit-addition': typeof GameTwoDigitAdditionRoute
  '/_game/two-digit-subtraction': typeof GameTwoDigitSubtractionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eleven'
    | '/multiplication'
    | '/one-digit-addition'
    | '/one-digit-subtraction'
    | '/power-of-two'
    | '/two-digit-addition'
    | '/two-digit-subtraction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eleven'
    | '/multiplication'
    | '/one-digit-addition'
    | '/one-digit-subtraction'
    | '/power-of-two'
    | '/two-digit-addition'
    | '/two-digit-subtraction'
  id:
    | '__root__'
    | '/'
    | '/_game'
    | '/_game/eleven'
    | '/_game/multiplication'
    | '/_game/one-digit-addition'
    | '/_game/one-digit-subtraction'
    | '/_game/power-of-two'
    | '/_game/two-digit-addition'
    | '/_game/two-digit-subtraction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameRouteRoute: typeof GameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_game': {
      id: '/_game'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/two-digit-subtraction': {
      id: '/_game/two-digit-subtraction'
      path: '/two-digit-subtraction'
      fullPath: '/two-digit-subtraction'
      preLoaderRoute: typeof GameTwoDigitSubtractionRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/two-digit-addition': {
      id: '/_game/two-digit-addition'
      path: '/two-digit-addition'
      fullPath: '/two-digit-addition'
      preLoaderRoute: typeof GameTwoDigitAdditionRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/power-of-two': {
      id: '/_game/power-of-two'
      path: '/power-of-two'
      fullPath: '/power-of-two'
      preLoaderRoute: typeof GamePowerOfTwoRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/one-digit-subtraction': {
      id: '/_game/one-digit-subtraction'
      path: '/one-digit-subtraction'
      fullPath: '/one-digit-subtraction'
      preLoaderRoute: typeof GameOneDigitSubtractionRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/one-digit-addition': {
      id: '/_game/one-digit-addition'
      path: '/one-digit-addition'
      fullPath: '/one-digit-addition'
      preLoaderRoute: typeof GameOneDigitAdditionRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/multiplication': {
      id: '/_game/multiplication'
      path: '/multiplication'
      fullPath: '/multiplication'
      preLoaderRoute: typeof GameMultiplicationRouteImport
      parentRoute: typeof GameRouteRoute
    }
    '/_game/eleven': {
      id: '/_game/eleven'
      path: '/eleven'
      fullPath: '/eleven'
      preLoaderRoute: typeof GameElevenRouteImport
      parentRoute: typeof GameRouteRoute
    }
  }
}

interface GameRouteRouteChildren {
  GameElevenRoute: typeof GameElevenRoute
  GameMultiplicationRoute: typeof GameMultiplicationRoute
  GameOneDigitAdditionRoute: typeof GameOneDigitAdditionRoute
  GameOneDigitSubtractionRoute: typeof GameOneDigitSubtractionRoute
  GamePowerOfTwoRoute: typeof GamePowerOfTwoRoute
  GameTwoDigitAdditionRoute: typeof GameTwoDigitAdditionRoute
  GameTwoDigitSubtractionRoute: typeof GameTwoDigitSubtractionRoute
}

const GameRouteRouteChildren: GameRouteRouteChildren = {
  GameElevenRoute: GameElevenRoute,
  GameMultiplicationRoute: GameMultiplicationRoute,
  GameOneDigitAdditionRoute: GameOneDigitAdditionRoute,
  GameOneDigitSubtractionRoute: GameOneDigitSubtractionRoute,
  GamePowerOfTwoRoute: GamePowerOfTwoRoute,
  GameTwoDigitAdditionRoute: GameTwoDigitAdditionRoute,
  GameTwoDigitSubtractionRoute: GameTwoDigitSubtractionRoute,
}

const GameRouteRouteWithChildren = GameRouteRoute._addFileChildren(
  GameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameRouteRoute: GameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
